// This generates a Vscode theme automatically

// Some Solarized colors are used

// raw data from coolors
const coolors_raw =
  "https://coolors.co/ffdddd-bbffbb-003300-220000-ee5599-ee9955-5599ee";

const coolors = coolors_raw
  .split("https://coolors.co/")[1]
  .split("-")
  .map((x) => "#" + x);

let [b_light, f_dark, f_light, b_dark, h_red, h_default, h_blue] = coolors;

// Initially I tried to make a dark-and-light theme, but it didn't work.
// VSCode needs more flexibility for this to work.
f_dark = f_light;
b_dark = b_light;

const vstheme_main_raw = {
  $schema: "vscode://schemas/color-theme",
  name: "Light+ (default light)",
  include: "./light_vs.json",
  tokenColors: [
    // adds rules to the light vs rules
    {
      name: "Function declarations",
      scope: [
        "entity.name.function",
        "support.function",
        "support.constant.handlebars",
        "source.powershell variable.other.member",
        "entity.name.operator.custom-literal", // See https://en.cppreference.com/w/cpp/language/user_literal
      ],
      settings: {
        foreground: "#795E26",
      },
    },
    {
      name: "Types declaration and references",
      scope: [
        "meta.return-type",
        "support.class",
        "support.type",
        "entity.name.type",
        "entity.name.namespace",
        "entity.other.attribute",
        "entity.name.scope-resolution",
        "entity.name.class",
        "storage.type.numeric.go",
        "storage.type.byte.go",
        "storage.type.boolean.go",
        "storage.type.string.go",
        "storage.type.uintptr.go",
        "storage.type.error.go",
        "storage.type.rune.go",
        "storage.type.cs",
        "storage.type.generic.cs",
        "storage.type.modifier.cs",
        "storage.type.variable.cs",
        "storage.type.annotation.java",
        "storage.type.generic.java",
        "storage.type.java",
        "storage.type.object.array.java",
        "storage.type.primitive.array.java",
        "storage.type.primitive.java",
        "storage.type.token.java",
        "storage.type.groovy",
        "storage.type.annotation.groovy",
        "storage.type.parameters.groovy",
        "storage.type.generic.groovy",
        "storage.type.object.array.groovy",
        "storage.type.primitive.array.groovy",
        "storage.type.primitive.groovy",
      ],
      settings: {
        foreground: "#267f99",
      },
    },
    {
      name: "Types declaration and references, TS grammar specific",
      scope: [
        "meta.type.cast.expr",
        "meta.type.new.expr",
        "support.constant.math",
        "support.constant.dom",
        "support.constant.json",
        "entity.other.inherited-class",
      ],
      settings: {
        foreground: "#267f99",
      },
    },
    {
      name: "Control flow / Special keywords",
      scope: [
        "keyword.control",
        "source.cpp keyword.operator.new",
        "source.cpp keyword.operator.delete",
        "keyword.other.using",
        "keyword.other.operator",
        "entity.name.operator",
      ],
      settings: {
        foreground: "#AF00DB",
      },
    },
    {
      name: "Variable and parameter name",
      scope: [
        "variable",
        "meta.definition.variable.name",
        "support.variable",
        "entity.name.variable",
      ],
      settings: {
        foreground: "#001080",
      },
    },
    {
      name: "Constants and enums",
      scope: ["variable.other.constant", "variable.other.enummember"],
      settings: {
        foreground: "#0070C1",
      },
    },
    {
      name: "Object keys, TS grammar specific",
      scope: ["meta.object-literal.key"],
      settings: {
        foreground: "#001080",
      },
    },
    {
      name: "CSS property value",
      scope: [
        "support.constant.property-value",
        "support.constant.font-name",
        "support.constant.media-type",
        "support.constant.media",
        "constant.other.color.rgb-value",
        "constant.other.rgb-value",
        "support.constant.color",
      ],
      settings: {
        foreground: "#0451a5",
      },
    },
    {
      name: "Regular expression groups",
      scope: [
        "punctuation.definition.group.regexp",
        "punctuation.definition.group.assertion.regexp",
        "punctuation.definition.character-class.regexp",
        "punctuation.character.set.begin.regexp",
        "punctuation.character.set.end.regexp",
        "keyword.operator.negation.regexp",
        "support.other.parenthesis.regexp",
      ],
      settings: {
        foreground: "#d16969",
      },
    },
    {
      scope: [
        "constant.character.character-class.regexp",
        "constant.other.character-class.set.regexp",
        "constant.other.character-class.regexp",
        "constant.character.set.regexp",
      ],
      settings: {
        foreground: "#811f3f",
      },
    },
    {
      scope: "keyword.operator.quantifier.regexp",
      settings: {
        foreground: "#000000",
      },
    },
    {
      scope: ["keyword.operator.or.regexp", "keyword.control.anchor.regexp"],
      settings: {
        foreground: "#EE0000",
      },
    },
    {
      scope: "constant.character",
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: "constant.character.escape",
      settings: {
        foreground: "#EE0000",
      },
    },
    {
      scope: "entity.name.label",
      settings: {
        foreground: "#000000",
      },
    },
  ],
  semanticHighlighting: true,
  semanticTokenColors: {
    newOperator: "#AF00DB",
    stringLiteral: "#a31515",
    customLiteral: "#795E26",
    numberLiteral: "#098658",
  },
};

const vstheme_base_raw = {
  $schema: "vscode://schemas/color-theme",
  name: "Light (Visual Studio)",
  colors: {
    "editor.background": "#FFFFFF",
    "editor.foreground": "#000000",
    "editor.inactiveSelectionBackground": "#E5EBF1",
    "editorIndentGuide.background": "#D3D3D3",
    "editorIndentGuide.activeBackground": "#939393",
    "editor.selectionHighlightBackground": "#ADD6FF80",
    "editorSuggestWidget.background": "#F3F3F3",
    "activityBarBadge.background": "#007ACC",
    "sideBarTitle.foreground": "#6F6F6F",
    "list.hoverBackground": "#E8E8E8",
    "input.placeholderForeground": "#767676",
    "searchEditor.textInputBorder": "#CECECE",
    "settings.textInputBorder": "#CECECE",
    "settings.numberInputBorder": "#CECECE",
    "statusBarItem.remoteForeground": "#FFF",
    "statusBarItem.remoteBackground": "#16825D",
    "sideBarSectionHeader.background": "#0000",
    "sideBarSectionHeader.border": "#61616130",
    "tab.lastPinnedBorder": "#61616130",
    "notebook.cellBorderColor": "#E8E8E8",
    "notebook.selectedCellBackground": "#c8ddf150",
    "statusBarItem.errorBackground": "#c72e0f",
  },
  tokenColors: [
    {
      scope: ["meta.embedded", "source.groovy.embedded"],
      settings: {
        foreground: "#000000ff",
      },
    },
    {
      scope: "emphasis",
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: "strong",
      settings: {
        fontStyle: "bold",
      },
    },
    {
      scope: "meta.diff.header",
      settings: {
        foreground: "#000080",
      },
    },
    {
      scope: "comment",
      settings: {
        foreground: "#008000",
      },
    },
    {
      scope: "constant.language",
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: [
        "constant.numeric",
        "variable.other.enummember",
        "keyword.operator.plus.exponent",
        "keyword.operator.minus.exponent",
      ],
      settings: {
        foreground: "#098658",
      },
    },
    {
      scope: "constant.regexp",
      settings: {
        foreground: "#811f3f",
      },
    },
    {
      name: "css tags in selectors, xml tags",
      scope: "entity.name.tag",
      settings: {
        foreground: "#800000",
      },
    },
    {
      scope: "entity.name.selector",
      settings: {
        foreground: "#800000",
      },
    },
    {
      scope: "entity.other.attribute-name",
      settings: {
        foreground: "#ff0000",
      },
    },
    {
      scope: [
        "entity.other.attribute-name.class.css",
        "entity.other.attribute-name.class.mixin.css",
        "entity.other.attribute-name.id.css",
        "entity.other.attribute-name.parent-selector.css",
        "entity.other.attribute-name.pseudo-class.css",
        "entity.other.attribute-name.pseudo-element.css",
        "source.css.less entity.other.attribute-name.id",
        "entity.other.attribute-name.scss",
      ],
      settings: {
        foreground: "#800000",
      },
    },
    {
      scope: "invalid",
      settings: {
        foreground: "#cd3131",
      },
    },
    {
      scope: "markup.underline",
      settings: {
        fontStyle: "underline",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        fontStyle: "bold",
        foreground: "#000080",
      },
    },
    {
      scope: "markup.heading",
      settings: {
        fontStyle: "bold",
        foreground: "#800000",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: "markup.inserted",
      settings: {
        foreground: "#098658",
      },
    },
    {
      scope: "markup.deleted",
      settings: {
        foreground: "#a31515",
      },
    },
    {
      scope: "markup.changed",
      settings: {
        foreground: "#0451a5",
      },
    },
    {
      scope: [
        "punctuation.definition.quote.begin.markdown",
        "punctuation.definition.list.begin.markdown",
      ],
      settings: {
        foreground: "#0451a5",
      },
    },
    {
      scope: "markup.inline.raw",
      settings: {
        foreground: "#800000",
      },
    },
    {
      name: "brackets of XML/HTML tags",
      scope: "punctuation.definition.tag",
      settings: {
        foreground: "#800000",
      },
    },
    {
      scope: ["meta.preprocessor", "entity.name.function.preprocessor"],
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: "meta.preprocessor.string",
      settings: {
        foreground: "#a31515",
      },
    },
    {
      scope: "meta.preprocessor.numeric",
      settings: {
        foreground: "#098658",
      },
    },
    {
      scope: "meta.structure.dictionary.key.python",
      settings: {
        foreground: "#0451a5",
      },
    },
    {
      scope: "storage",
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: "storage.type",
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: ["storage.modifier", "keyword.operator.noexcept"],
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: ["string", "meta.embedded.assembly"],
      settings: {
        foreground: "#a31515",
      },
    },
    {
      scope: [
        "string.comment.buffered.block.pug",
        "string.quoted.pug",
        "string.interpolated.pug",
        "string.unquoted.plain.in.yaml",
        "string.unquoted.plain.out.yaml",
        "string.unquoted.block.yaml",
        "string.quoted.single.yaml",
        "string.quoted.double.xml",
        "string.quoted.single.xml",
        "string.unquoted.cdata.xml",
        "string.quoted.double.html",
        "string.quoted.single.html",
        "string.unquoted.html",
        "string.quoted.single.handlebars",
        "string.quoted.double.handlebars",
      ],
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: "string.regexp",
      settings: {
        foreground: "#811f3f",
      },
    },
    {
      name: "String interpolation",
      scope: [
        "punctuation.definition.template-expression.begin",
        "punctuation.definition.template-expression.end",
        "punctuation.section.embedded",
      ],
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      name: "Reset JavaScript string interpolation expression",
      scope: ["meta.template.expression"],
      settings: {
        foreground: "#000000",
      },
    },
    {
      scope: [
        "support.constant.property-value",
        "support.constant.font-name",
        "support.constant.media-type",
        "support.constant.media",
        "constant.other.color.rgb-value",
        "constant.other.rgb-value",
        "support.constant.color",
      ],
      settings: {
        foreground: "#0451a5",
      },
    },
    {
      scope: [
        "support.type.vendored.property-name",
        "support.type.property-name",
        "variable.css",
        "variable.scss",
        "variable.other.less",
        "source.coffee.embedded",
      ],
      settings: {
        foreground: "#ff0000",
      },
    },
    {
      scope: ["support.type.property-name.json"],
      settings: {
        foreground: "#0451a5",
      },
    },
    {
      scope: "keyword",
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: "keyword.control",
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: "keyword.operator",
      settings: {
        foreground: "#000000",
      },
    },
    {
      scope: [
        "keyword.operator.new",
        "keyword.operator.expression",
        "keyword.operator.cast",
        "keyword.operator.sizeof",
        "keyword.operator.alignof",
        "keyword.operator.typeid",
        "keyword.operator.alignas",
        "keyword.operator.instanceof",
        "keyword.operator.logical.python",
        "keyword.operator.wordlike",
      ],
      settings: {
        foreground: "#0000ff",
      },
    },
    {
      scope: "keyword.other.unit",
      settings: {
        foreground: "#098658",
      },
    },
    {
      scope: [
        "punctuation.section.embedded.begin.php",
        "punctuation.section.embedded.end.php",
      ],
      settings: {
        foreground: "#800000",
      },
    },
    {
      scope: "support.function.git-rebase",
      settings: {
        foreground: "#0451a5",
      },
    },
    {
      scope: "constant.sha.git-rebase",
      settings: {
        foreground: "#098658",
      },
    },
    {
      name: "coloring of the Java import and package identifiers",
      scope: [
        "storage.modifier.import.java",
        "variable.language.wildcard.java",
        "storage.modifier.package.java",
      ],
      settings: {
        foreground: "#000000",
      },
    },
    {
      name: "this.self",
      scope: "variable.language",
      settings: {
        foreground: "#0000ff",
      },
    },
  ],
  semanticHighlighting: true,
  semanticTokenColors: {
    newOperator: "#0000ff",
    stringLiteral: "#a31515",
    customLiteral: "#000000",
    numberLiteral: "#098658",
  },
};

const token_colors: any = (vstheme_main_raw.tokenColors as any).concat(
  vstheme_base_raw.tokenColors as any
);

token_colors.forEach(
  (x: any) =>
    (x.settings = {
      foreground: f_light,
    })
);

const str_wcc = "workbench.colorCustomizations";
const str_tcc = "editor.tokenColorCustomizations";

const settings_obj = {
  [str_wcc]: {
    "list.errorForeground": "#00000050",
    "list.warningForeground": "#00000050",
    "editorOverviewRuler.bracketMatchForeground": "#00000000",
    "editorError.background": "#00000000",
    "editorWarning.background": "#00000000",
    "editorInfo.background": "#00000000",
    contrastActiveBorder: "#00000050",
    contrastBorder: "#00000050",
    "scrollbarSlider.activeBackground": "#00000050",
    "scrollbarSlider.background": "#00000050",
    "scrollbarSlider.hoverBackground": "#00000050",
    "badge.foreground": "#00000050",
    "badge.background": "#00000050",
    "list.dropBackground": "#00000050",
    "activityBarBadge.background": "#00000050",
    "activityBarBadge.foreground": "#00000050",
    "sideBar.dropBackground": "#00000050",
    "minimapSlider.background": "#00000050",
    "minimapSlider.hoverBackground": "#00000050",
    "minimapSlider.activeBackground": "#00000050",
    "editorGroup.dropBackground": "#00000050",
    "editor.inactiveSelectionBackground": "#00000050",
    "editor.selectionHighlightBackground": "#00000050",
    "editor.wordHighlightBackground": "#00000050",
    "editor.wordHighlightStrongBackground": "#00000050",
    "editor.findMatchHighlightBackground": "#00000050",
    "editor.findRangeHighlightBackground": "#00000050",
    "editor.hoverHighlightBackground": "#00000050",
    "editor.foldBackground": "#00000050",
    "editorOverviewRuler.findMatchForeground": "#00000050",
    "editorOverviewRuler.rangeHighlightForeground": "#00000050",
    "editorOverviewRuler.selectionHighlightForeground": "#00000050",
    "editorOverviewRuler.wordHighlightForeground": "#00000050",
    "editorOverviewRuler.wordHighlightStrongForeground": "#00000050",
    "diffEditor.insertedTextBackground": "#00000050",
    "diffEditor.removedTextBackground": "#00000050",
    "merge.currentHeaderBackground": "#00000050",
    "merge.currentContentBackground": "#00000050",
    "merge.incomingHeaderBackground": "#00000050",
    "merge.incomingContentBackground": "#00000050",
    "merge.commonContentBackground": "#00000050",
    "merge.commonHeaderBackground": "#00000050",
    "panelSection.dropBackground": "#00000050",
    "extensionBadge.remoteBackground": "#00000050",
    "extensionBadge.remoteForeground": "#00000050",
    "editorUnnecessaryCode.opacity": "#00000050",
    foreground: f_dark,
    "inputValidation.errorBorder": b_dark,
    "inputValidation.infoBorder": b_dark,
    "inputValidation.warningBorder": b_dark,
    "listFilterWidget.background": b_dark,
    "list.filterMatchBackground": b_dark,
    "activityBar.background": b_dark,
    "activityBar.activeBackground": b_dark,
    "sideBar.background": b_dark,
    "minimap.background": b_light,
    "editorGroupHeader.noTabsBackground": b_dark,
    "editorGroupHeader.tabsBackground": b_dark,
    "editorGroup.emptyBackground": b_dark,
    "tab.activeBackground": b_dark,
    "tab.unfocusedActiveBackground": b_dark,
    "tab.inactiveBackground": b_dark,
    "tab.unfocusedInactiveBackground": b_dark,
    "searchEditor.findMatchBackground": b_dark,
    "diffEditor.diagonalFill": b_dark,
    "debugExceptionWidget.background": b_dark,
    "editorMarkerNavigation.background": b_dark,
    "panel.background": b_dark,
    "panelSectionHeader.background": b_dark,
    "statusBar.background": b_dark,
    "statusBar.debuggingBackground": b_dark,
    "statusBar.noFolderForeground": b_dark,
    "menubar.selectionBackground": b_dark,
    "menu.background": b_dark,
    "menu.selectionBackground": b_dark,
    "notificationCenterHeader.background": b_dark,
    "notifications.background": b_dark,
    "quickInput.background": b_dark,
    "quickInputTitle.background": b_dark,
    "terminal.background": b_dark,
    "debugToolBar.background": b_dark,
    "debugView.exceptionLabelBackground": b_dark,
    "debugView.stateLabelBackground": b_dark,
    "welcomePage.background": b_light,
    "breadcrumb.background": b_dark,
    "breadcrumbPicker.background": b_dark,
    "textBlockQuote.background": b_light,
    "textCodeBlock.background": b_light,
    "scrollbar.shadow": h_blue,
    "editor.background": b_light,
    "editor.findMatchBackground": b_light,
    "editor.lineHighlightBackground": b_light,
    "editor.rangeHighlightBackground": b_light,
    "editor.symbolHighlightBackground": b_light,
    "editor.linkedEditingBackground": b_light,
    "editorWidget.background": b_dark,
    "editorSuggestWidget.background": b_light,
    "editorHoverWidget.background": b_light,
    "editorHoverWidget.statusBarBackground": b_light,
    "peekViewEditor.background": b_light,
    "peekViewEditorGutter.background": b_light,
    "peekViewEditor.matchHighlightBackground": b_light,
    "peekViewResult.background": b_light,
    "peekViewTitle.background": b_light,
    "walkThrough.embeddedEditorBackground": b_light,
    "settings.dropdownBackground": b_light,
    "settings.checkboxBackground": b_light,
    "settings.textInputBackground": b_light,
    "settings.numberInputBackground": b_light,
    "settings.focusedRowBackground": b_light,
    "notebook.rowHoverBackground": b_light,
    "editor.snippetTabstopHighlightBackground": b_light,
    "editor.snippetFinalTabstopHighlightBackground": b_light,
    "notebook.outputContainerBackgroundColor": b_light,
    "notebook.focusedCellBackground": b_light,
    "notebook.cellStatusBarItemHoverBackground": b_light,
    descriptionForeground: f_dark,
    errorForeground: f_dark,
    "icon.foreground": f_dark,
    "button.foreground": f_dark,
    "button.secondaryForeground": f_dark,
    "checkbox.foreground": f_dark,
    "dropdown.foreground": f_dark,
    "input.foreground": f_dark,
    "input.placeholderForeground": f_dark,
    "inputOption.activeForeground": f_dark,
    "inputValidation.errorForeground": f_dark,
    "inputValidation.infoForeground": f_dark,
    "inputValidation.warningForeground": f_dark,
    "list.activeSelectionForeground": f_dark,
    "list.focusForeground": f_dark,
    "list.hoverForeground": f_dark,
    "list.inactiveSelectionForeground": f_dark,
    "list.invalidItemForeground": f_dark,
    "list.deemphasizedForeground": f_dark,
    "activityBar.foreground": f_dark,
    "activityBar.inactiveForeground": f_dark,
    "sideBar.foreground": f_dark,
    "sideBarTitle.foreground": f_dark,
    "sideBarSectionHeader.foreground": f_dark,
    "tab.activeForeground": f_dark,
    "tab.inactiveForeground": f_dark,
    "tab.unfocusedActiveForeground": f_dark,
    "tab.unfocusedInactiveForeground": f_dark,
    "tab.hoverForeground": f_dark,
    "tab.unfocusedHoverForeground": f_dark,
    "panelTitle.activeForeground": f_dark,
    "panelTitle.inactiveForeground": f_dark,
    "panelSectionHeader.foreground": f_dark,
    "statusBar.foreground": f_dark,
    "statusBar.debuggingForeground": f_dark,
    "statusBar.noFolderBackground": f_dark,
    "statusBarItem.prominentForeground": f_dark,
    "statusBarItem.prominentBackground": f_dark,
    "statusBarItem.remoteForeground": f_dark,
    "statusBarItem.errorForeground": f_dark,
    "titleBar.activeForeground": f_dark,
    "titleBar.inactiveForeground": f_dark,
    "menubar.selectionForeground": f_dark,
    "menu.foreground": f_dark,
    "menu.selectionForeground": f_dark,
    "notificationCenterHeader.foreground": f_dark,
    "notifications.foreground": f_dark,
    "notificationLink.foreground": f_dark,
    "extensionButton.prominentForeground": f_dark,
    "pickerGroup.foreground": f_dark,
    "quickInput.foreground": f_dark,
    "terminal.foreground": f_dark,
    "debugView.exceptionLabelForeground": f_dark,
    "debugView.stateLabelForeground": f_dark,
    "debugTokenExpression.name": f_dark,
    "debugTokenExpression.value": f_dark,
    "debugTokenExpression.string": f_dark,
    "debugTokenExpression.boolean": f_dark,
    "debugTokenExpression.number": f_dark,
    "debugTokenExpression.error": f_dark,
    "testing.message.error.decorationForeground": f_dark,
    "testing.message.warning.decorationForeground": f_dark,
    "testing.message.info.decorationForeground": f_dark,
    "testing.message.hint.decorationForeground": f_dark,
    "breadcrumb.foreground": f_dark,
    "symbolIcon.arrayForeground": f_dark,
    "symbolIcon.booleanForeground": f_dark,
    "symbolIcon.classForeground": f_dark,
    "symbolIcon.colorForeground": f_dark,
    "symbolIcon.constantForeground": f_dark,
    "symbolIcon.constructorForeground": f_dark,
    "symbolIcon.enumeratorForeground": f_dark,
    "symbolIcon.enumeratorMemberForeground": f_dark,
    "symbolIcon.eventForeground": f_dark,
    "symbolIcon.fieldForeground": f_dark,
    "symbolIcon.fileForeground": f_dark,
    "symbolIcon.folderForeground": f_dark,
    "symbolIcon.functionForeground": f_dark,
    "symbolIcon.interfaceForeground": f_dark,
    "symbolIcon.keyForeground": f_dark,
    "symbolIcon.keywordForeground": f_dark,
    "symbolIcon.methodForeground": f_dark,
    "symbolIcon.moduleForeground": f_dark,
    "symbolIcon.namespaceForeground": f_dark,
    "symbolIcon.nullForeground": f_dark,
    "symbolIcon.numberForeground": f_dark,
    "symbolIcon.objectForeground": f_dark,
    "symbolIcon.operatorForeground": f_dark,
    "symbolIcon.packageForeground": f_dark,
    "symbolIcon.propertyForeground": f_dark,
    "symbolIcon.referenceForeground": f_dark,
    "symbolIcon.snippetForeground": f_dark,
    "symbolIcon.stringForeground": f_dark,
    "symbolIcon.structForeground": f_dark,
    "symbolIcon.textForeground": f_dark,
    "symbolIcon.typeParameterForeground": f_dark,
    "symbolIcon.unitForeground": f_dark,
    "symbolIcon.variableForeground": f_dark,
    "debugConsole.infoForeground": f_dark,
    "debugConsole.warningForeground": f_dark,
    "debugConsole.errorForeground": f_dark,
    "debugConsole.sourceForeground": f_dark,
    "debugConsoleInputIcon.foreground": f_dark,
    "textLink.foreground": f_light,
    "textPreformat.foreground": f_light,
    "textSeparator.foreground": f_light,
    "editor.foreground": f_light,
    "editor.selectionForeground": f_light,
    "editorWhitespace.foreground": f_light,
    "editorCodeLens.foreground": f_light,
    "editorBracketMatch.background": b_light,
    "editorOverviewRuler.background": b_light,
    "editorHint.foreground": f_light,
    "editorGutter.background": b_light,
    "editorWidget.foreground": f_dark,
    "editorSuggestWidget.foreground": f_light,
    "editorHoverWidget.foreground": f_light,
    "peekViewResult.fileForeground": f_light,
    "peekViewResult.lineForeground": f_light,
    "peekViewResult.selectionForeground": f_light,
    "peekViewTitleDescription.foreground": f_light,
    "peekViewTitleLabel.foreground": f_light,
    "editorOverviewRuler.currentContentForeground": f_light,
    "editorOverviewRuler.incomingContentForeground": f_light,
    "editorOverviewRuler.commonContentForeground": f_light,
    "settings.dropdownForeground": f_light,
    "settings.checkboxForeground": f_light,
    "settings.textInputForeground": f_light,
    "settings.numberInputForeground": f_light,
    "charts.foreground": f_light,
    "charts.lines": f_light,
    "widget.shadow": h_blue,
    "window.inactiveBorder": h_blue,
    "textBlockQuote.border": h_blue,
    "button.secondaryBackground": h_blue,
    "checkbox.border": h_blue,
    "dropdown.border": h_blue,
    "input.border": h_blue,
    "inputValidation.infoBackground": h_blue,
    "inputValidation.warningBackground": h_blue,
    "list.highlightForeground": h_blue,
    "list.inactiveSelectionBackground": h_blue,
    "list.inactiveFocusBackground": h_blue,
    "listFilterWidget.noMatchesOutline": h_blue,
    "sideBar.border": h_blue,
    "sideBarSectionHeader.border": h_blue,
    "minimap.findMatchHighlight": h_blue,
    "minimapGutter.deletedBackground": h_blue,
    "editorGroup.border": h_blue,
    "editorGroupHeader.tabsBorder": h_blue,
    "editorGroupHeader.border": h_blue,
    "tab.border": h_blue,
    "tab.unfocusedActiveBorder": h_blue,
    "tab.unfocusedActiveBorderTop": h_blue,
    "editor.selectionHighlightBorder": h_blue,
    "editor.findMatchHighlightBorder": h_blue,
    "editorOverviewRuler.deletedForeground": h_blue,
    "editorGutter.deletedBackground": h_blue,
    "diffEditor.removedTextBorder": h_blue,
    "diffEditor.border": h_blue,
    "editorWidget.border": h_blue,
    "editorWidget.resizeBorder": h_blue,
    "editorSuggestWidget.border": h_blue,
    "editorHoverWidget.border": h_blue,
    "debugExceptionWidget.border": h_blue,
    "editorMarkerNavigationInfo.background": h_blue,
    "peekView.border": h_blue,
    "merge.border": h_blue,
    "panel.border": h_blue,
    "panelSection.border": h_blue,
    "panelSectionHeader.border": h_blue,
    "imagePreview.border": h_blue,
    "statusBar.border": h_blue,
    "statusBar.debuggingBorder": h_blue,
    "statusBar.noFolderBorder": h_blue,
    "titleBar.inactiveBackground": h_blue,
    "titleBar.border": h_blue,
    "menu.border": h_blue,
    "notificationCenter.border": h_blue,
    "notificationToast.border": h_blue,
    "notifications.border": h_blue,
    "notificationsInfoIcon.foreground": h_blue,
    "pickerGroup.border": h_blue,
    "terminal.border": h_blue,
    "debugToolBar.border": h_blue,
    "testing.iconQueued": h_blue,
    "testing.iconUnset": h_blue,
    "testing.iconSkipped": h_blue,
    "testing.message.info.lineBackground": h_blue,
    "testing.message.hint.lineBackground": h_blue,
    "scm.providerBorder": h_blue,
    "gitDecoration.deletedResourceForeground": h_blue,
    "gitDecoration.stageDeletedResourceForeground": h_blue,
    "gitDecoration.untrackedResourceForeground": h_blue,
    "gitDecoration.ignoredResourceForeground": h_blue,
    "gitDecoration.submoduleResourceForeground": h_blue,
    "settings.dropdownBorder": h_blue,
    "settings.dropdownListBorder": h_blue,
    "settings.checkboxBorder": h_blue,
    "settings.textInputBorder": h_blue,
    "settings.numberInputBorder": h_blue,
    "notebook.focusedRowBorder": h_blue,
    "debugIcon.breakpointDisabledForeground": h_blue,
    "debugIcon.breakpointUnverifiedForeground": h_blue,
    "notebook.cellBorderColor": h_blue,
    "notebookStatusRunningIcon.foreground": h_blue,
    "notebook.cellToolbarSeparator": h_blue,
    "notebook.focusedCellShadow": h_blue,
    "notebook.inactiveFocusedCellBorder": h_blue,
    "testing.peekBorder": h_blue,
    "selection.background": h_default,
    "button.background": h_default,
    "checkbox.background": h_default,
    "dropdown.background": h_default,
    "dropdown.listBackground": h_default,
    "input.background": h_default,
    "inputOption.activeBackground": h_default,
    "list.focusBackground": h_default,
    "tree.indentGuidesStroke": h_default,
    "sideBarSectionHeader.background": h_default,
    "minimap.selectionHighlight": h_default,
    "minimapGutter.addedBackground": h_default,
    "minimapGutter.modifiedBackground": h_default,
    "tab.lastPinnedBorder": h_default,
    "editorLineNumber.foreground": h_default,
    "editor.findRangeHighlightBorder": h_default,
    "searchEditor.textInputBorder": h_default,
    "editorIndentGuide.background": h_default,
    "editorOverviewRuler.border": h_default,
    "editorOverviewRuler.modifiedForeground": h_default,
    "editorOverviewRuler.addedForeground": h_default,
    "editorGutter.modifiedBackground": h_default,
    "editorGutter.addedBackground": h_default,
    "diffEditor.insertedTextBorder": h_default,
    "editorMarkerNavigationWarning.background": h_default,
    "peekViewResult.selectionBackground": h_default,
    "statusBarItem.remoteBackground": h_default,
    "menu.separatorBackground": h_default,
    "notificationsWarningIcon.foreground": h_default,
    "extensionButton.prominentBackground": h_default,
    "terminal.selectionBackground": h_default,
    "editor.stackFrameHighlightBackground": h_default,
    "debugView.valueChangedHighlight": h_default,
    "testing.iconPassed": h_default,
    "testing.runAction": h_default,
    "testing.message.warning.lineBackground": h_default,
    "welcomePage.buttonBackground": h_default,
    "gitDecoration.addedResourceForeground": h_default,
    "gitDecoration.modifiedResourceForeground": h_default,
    "gitDecoration.stageModifiedResourceForeground": h_default,
    "settings.modifiedItemIndicator": h_default,
    "breadcrumb.focusForeground": h_default,
    "breadcrumb.activeSelectionForeground": h_default,
    "debugIcon.breakpointForeground": h_default,
    "debugIcon.breakpointCurrentStackframeForeground": h_default,
    "debugIcon.breakpointStackframeForeground": h_default,
    "debugIcon.startForeground": h_default,
    "debugIcon.pauseForeground": h_default,
    "debugIcon.stopForeground": h_default,
    "debugIcon.disconnectForeground": h_default,
    "debugIcon.restartForeground": h_default,
    "debugIcon.stepOverForeground": h_default,
    "debugIcon.stepIntoForeground": h_default,
    "debugIcon.stepOutForeground": h_default,
    "debugIcon.continueForeground": h_default,
    "debugIcon.stepBackForeground": h_default,
    "notebookStatusSuccessIcon.foreground": h_default,
    "notebookScrollbarSlider.background": h_default,
    "notebook.symbolHighlightBackground": h_default,
    focusBorder: h_red,
    "sash.hoverBorder": h_red,
    "window.activeBorder": h_red,
    "textLink.activeForeground": h_red,
    "button.hoverBackground": h_red,
    "button.secondaryHoverBackground": h_red,
    "inputOption.activeBorder": h_red,
    "inputValidation.errorBackground": h_red,
    "progressBar.background": h_red,
    "list.activeSelectionBackground": h_red,
    "list.hoverBackground": h_red,
    "listFilterWidget.outline": h_red,
    "list.filterMatchBorder": h_red,
    "activityBar.dropBorder": h_red,
    "activityBar.border": h_red,
    "activityBar.activeBorder": h_red,
    "activityBar.activeFocusBorder": h_red,
    "minimap.errorHighlight": h_red,
    "minimap.warningHighlight": h_red,
    "editorGroup.focusedEmptyBorder": h_red,
    "tab.activeBorder": h_red,
    "tab.activeBorderTop": h_red,
    "tab.hoverBackground": h_red,
    "tab.unfocusedHoverBackground": h_red,
    "tab.hoverBorder": h_red,
    "tab.unfocusedHoverBorder": h_red,
    "tab.activeModifiedBorder": h_red,
    "tab.inactiveModifiedBorder": h_red,
    "tab.unfocusedActiveModifiedBorder": h_red,
    "tab.unfocusedInactiveModifiedBorder": h_red,
    "editorLineNumber.activeForeground": h_red,
    "editorCursor.background": h_red,
    "editorCursor.foreground": h_red,
    "editor.selectionBackground": h_red,
    "editor.wordHighlightBorder": h_red,
    "editor.wordHighlightStrongBorder": h_red,
    "editor.findMatchBorder": h_red,
    "searchEditor.findMatchBorder": h_red,
    "editor.lineHighlightBorder": h_red,
    "editorLink.activeForeground": h_red,
    "editor.rangeHighlightBorder": h_red,
    "editor.symbolHighlightBorder": h_red,
    "editorIndentGuide.activeBackground": h_red,
    "editorRuler.foreground": h_red,
    "editorLightBulb.foreground": h_red,
    "editorLightBulbAutoFix.foreground": h_red,
    "editorBracketMatch.border": h_red,
    "editorOverviewRuler.errorForeground": h_red,
    "editorOverviewRuler.warningForeground": h_red,
    "editorOverviewRuler.infoForeground": h_red,
    "editorError.foreground": h_red,
    "editorError.border": h_red,
    "editorWarning.foreground": h_red,
    "editorWarning.border": h_red,
    "editorInfo.foreground": h_red,
    "editorInfo.border": h_red,
    "editorHint.border": h_red,
    "problemsErrorIcon.foreground": h_red,
    "problemsWarningIcon.foreground": h_red,
    "problemsInfoIcon.foreground": h_red,
    "editorUnnecessaryCode.border": h_red,
    "editorGutter.commentRangeForeground": h_red,
    "editorGutter.foldingControlForeground": h_red,
    "editorSuggestWidget.highlightForeground": h_red,
    "editorSuggestWidget.selectedBackground": h_red,
    "editorMarkerNavigationError.background": h_red,
    "peekViewEditor.matchHighlightBorder": h_red,
    "peekViewResult.matchHighlightBackground": h_red,
    "panel.dropBorder": h_red,
    "panelTitle.activeBorder": h_red,
    "statusBarItem.activeBackground": h_red,
    "statusBarItem.hoverBackground": h_red,
    "statusBarItem.prominentHoverBackground": h_red,
    "statusBarItem.errorBackground": h_red,
    "titleBar.activeBackground": h_red,
    "menubar.selectionBorder": h_red,
    "menu.selectionBorder": h_red,
    "notificationsErrorIcon.foreground": h_red,
    "extensionButton.prominentHoverBackground": h_red,
    "terminalCursor.background": h_red,
    "terminalCursor.foreground": h_red,
    "editor.focusedStackFrameHighlightBackground": h_red,
    "testing.iconFailed": h_red,
    "testing.iconErrored": h_red,
    "testing.message.error.lineBackground": h_red,
    "welcomePage.buttonHoverBackground": h_red,
    "welcomePage.progress.background": h_red,
    "welcomePage.progress.foreground": h_red,
    "gitDecoration.conflictingResourceForeground": h_red,
    "settings.headerForeground": h_red,
    "editor.snippetTabstopHighlightBorder": h_red,
    "editor.snippetFinalTabstopHighlightBorder": h_red,
    "notebook.focusedEditorBorder": h_red,
    "notebookStatusErrorIcon.foreground": h_red,
    "notebook.cellHoverBackground": h_red,
    "notebook.focusedCellBorder": h_red,
    "notebook.selectedCellBorder": h_red,
    "notebook.cellInsertionIndicator": h_red,
    "notebookScrollbarSlider.hoverBackground": h_red,
    "notebookScrollbarSlider.activeBackground": h_red,
  },
  [str_tcc]: {
    textMateRules: token_colors,
  },
  "editor.semanticTokenColorCustomizations": {
    enabled: true,
    rules: {
      newOperator: f_light,
      stringLiteral: f_light,
      customLiteral: f_light,
      numberLiteral: f_light,
    },
  },
  "window.zoomLevel": 2,
  "git.enableSmartCommit": true,
  "git.confirmSync": false,
  "dart.openDevTools": "flutter",
  "dart.debugExternalLibraries": false,
  "dart.debugSdkLibraries": false,
  "editor.fontFamily":
    "'Input', 'JetBrains Mono', Consolas, 'Courier New', monospace",
  "svelte.language-server.runtime": "C:\\Program Files\\nodejs\\node.exe",
  "editor.renderControlCharacters": false,
  "editor.renderWhitespace": "none",
  "dart.previewLsp": true,

  "bracket-pair-colorizer-2.colors": [
    //"#b58900",
    //"#cb4b16",
    //"#dc322f",
    "#d33682",
    "#6c71c4",
    "#268bd2",
    "#2aa198",
    "#859900",
  ],
  "bracketLens.color": "#dc322f",
  "bracketLens.prefix": " ... ",

  // The only reason why this is needed is because of VSCode's inability to format menu elements in their active state.
  "workbench.colorTheme": "Default Light+",
};

console.log(JSON.stringify(settings_obj));
